version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@date-io/dayjs"
      - dependency-name: "@material-ui/core"
