name: Deploy
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Update
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.AWS_REGION != '' }}
        uses: kazimanzurrashid/aws-static-web-app-update-action@v1
        with:
          location: ./build
          bucket: movement-pass.com
          cache-control: |
            public, max-age=31536000, immutable: ['**', '!./index.html', '!./manifest.json']
            max-age=0, no-cache, no-store, must-revalidate: ['./index.html']
          invalidate: true
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
